-- Note: This file should eventually go away, because enchanting is now done by _Automation.lua and the "-Filtered" files.
--       Almost everything that was in this file has been removed since it duplicated the recipes that are in the Automation/Filtered files.
--       But there are a couple sections remaining that can't be deleted yet until their information is moved to other files.  The Enchanting
--       Study section needs to have its items moved to the garrison vendor files.  The Illusions section probably needs to be moved to
--       Craftable Items.

-- Enchanting - Skill ID 333 / Spell ID 7411
profession(333, { -- Enchanting
	n(-25, { -- Pet Battles
		i(67274),	-- Enchanted Lantern
		i(67275),	-- Magic Lamp
	}),
	filter(27, { -- Wands
		i(11288),	-- Greater Magic Wand
		i(11290),	-- Greater Mystic Wan
		i(11287),	-- Lesser Magic Wand
		i(11289),	-- Lesser Mystic Wand
	}),
	filter(200, { 	-- Recipes
		-- Holiday
		n(-3, { 	-- Holiday
			recipe(46578),	-- Deathfrost
		}),
		tier(1, {	-- Classic
			recipe(7421),	-- Runed Copper Rod
			recipe(14807),	-- Greater Magic Wand
			recipe(14810),	-- Greater Mystic Wand
			recipe(14293),	-- Lesser Magic Wand
			recipe(14809),	-- Lesser Mystic Wand
			recipe(25125),	-- Minor Mana Oil
			recipe(25124),	-- Minor Wizard Oil
			recipe(25127),	-- Lesser Mana Oil
			recipe(25126),	-- Lesser Wizard Oil
			recipe(25128),	-- Wizard Oil
			un(2, recipe(25130)),	-- Formula: Brilliant Mana Oil
			un(2, recipe(25129)),	-- Formula: Brilliant Wizard Oil
			recipe(17181),	-- Enchanted Leather
			recipe(17180),	-- Enchanted Thorium Bar
			recipe(15596),	-- Smoking Heart of the Mountain
			recipe(7426),	-- Minor Absorption [Permanently enchant chest armor so it has a 2% chance per hit of giving you 10 points of damage absorption.]
			recipe(7779),	-- Minor Agility [Permanently enchant bracers to increase Agility by 1.]
			recipe(7867),	-- Minor Agility [Permanently enchant boots to increase Agility by 1.]
			recipe(13419),	-- Minor Agility [Permanently enchant a cloak to increase Agility by 1.]
			recipe(7786),	-- Minor Beastslayer [Permanently enchant a melee weapon to do 2 additional points of damage to beasts.]
			recipe(7428),	-- Minor Dodge [Permanently enchant bracers to increase dodge by 2.]
			recipe(13948),	-- Minor Haste [Permanently enchant gloves to increase haste by 6.]
			recipe(7418),	-- Minor Health [Permanently enchant bracers to increase health by 5.]
			recipe(7420),	-- Minor Health [Permanently enchant chest armor to increase health by 5.]
			recipe(7745),	-- Minor Impact [Permanently enchant a two-handed melee weapon to do 2 additional points of damage.]
			recipe(7443),	-- Minor Mana [Permanently enchant chest armor to increase mana by 3.]
			recipe(7771),	-- Minor Protection [Enchant a cloak to increase armor by 1.]
			recipe(13890),	-- Minor Speed [Permanently enchant boots to increase movement speed by 8%.]
			recipe(7457),	-- Minor Stamina [Permanently enchant bracers to increase Stamina by 1.]
			recipe(7863),	-- Minor Stamina [Permanently enchant boots to increase Stamina by 1.]
			recipe(13378),	-- Minor Stamina [Permanently enchant a shield to increase Stamina by 1.]
			recipe(13626),	-- Minor Stats [Permanently enchant chest armor to increase all stats by 1.]
			recipe(7782),	-- Minor Strength [Permanently enchant bracers to increase Strength by 1.]
			recipe(7788),	-- Minor Striking [Permanently enchant a melee weapon to do 1 additional point of damage.]
			recipe(7766),	-- Minor Versatility [Permanently enchant bracers to increase Versatility by 1.]
			recipe(13538),	-- Lesser Absorption [Permanently enchant chest armor so it has a 5% chance per hit of giving you 25 points of damage absorption.]
			recipe(63746),	-- Lesser Accuracy [Permanently enchant boots to increase crit by 2.]
			recipe(13637),	-- Lesser Agility [Permanently enchant boots to increase Agility by 3.]
			recipe(13882),	-- Lesser Agility [Permanently enchant a cloak to increase Agility by 3.]
			recipe(13653),	-- Lesser Beastslayer [Permanently enchant a melee weapon to increase damage to beasts by 6.]
			recipe(13646),	-- Lesser Dodge [Permanently enchant bracers to increase dodge by 3.]
			recipe(13655),	-- Lesser Elemental Slayer [Permanently enchant a melee weapon to increase damage to elementals by 6.]
			recipe(7748),	-- Lesser Health [Permanently enchant chest armor to increase health by 15.]
			recipe(13529),	-- Lesser Impact [Permanently enchant a two-handed melee weapon to do 3 additional points of damage.]
			recipe(7793),	-- Lesser Intellect [Permanently enchant a two-handed melee weapon to increase Intellect by 3.]
			recipe(13622),	-- Lesser Intellect [Permanently enchant bracers to increase Intellect by 3.]
			recipe(7776),	-- Lesser Mana [Permanently enchant chest armor to increase mana by 12.]
			recipe(13689),	-- Lesser Parry [Permanently enchant a shield to increase parry by 5.]
			recipe(13421),	-- Lesser Protection [Permanently enchant a cloak to increase armor by 2.]
			recipe(13464),	-- Lesser Protection [Permanently enchant a shield to increase armor by 3.]
			recipe(13501),	-- Lesser Stamina [Permanently enchant bracers to increase Stamina by 3.]
			recipe(13644),	-- Lesser Stamina [Permanently enchant boots to increase Stamina by 3.]
			recipe(13631),	-- Lesser Stamina [Permanently enchant a shield to increase Stamina by 3.]
			recipe(13700),	-- Lesser Stats [Permanently enchant chest armor to increase all stats by 2.]
			recipe(13536),	-- Lesser Strength [Permanently enchant bracers to increase Strength by 3.]
			recipe(13503),	-- Lesser Striking [Permanently enchant a melee weapon to do 2 additional points of damage.]
			recipe(13380),	-- Lesser Versatility [Permanently enchant a two-handed melee weapon to increase Versatility by 3.]
			recipe(7859),	-- Lesser Versatility [Permanently enchant bracers to increase Versatility by 3.]
			recipe(13687),	-- Lesser Versatility [Permanently enchant boots to increase Versatility by 3.]
			recipe(13485),	-- Lesser Versatility [Permanently enchant a shield to increase Versatility by 3.]
			recipe(13868),	-- Advanced Herbalism [Permanently enchant gloves to increase Herbalism skill by 5.]
			recipe(13841),	-- Advanced Mining [Permanently enchant gloves to increase Mining skill by 5.]
			recipe(13935),	-- Agility [Permanently enchant boots to increase Agility by 5.]
			recipe(13815),	-- Agility [Permanently enchant gloves to increase Agility by 5.]
			recipe(27837),	-- Agility [Permanently enchant a two-handed melee weapon to increase Agility by 25.]
			recipe(23800),	-- Agility [Permanently enchant a melee weapon to increase Agility by 15.]
			recipe(23801),	-- Argent Versatility [Permanently enchant bracers to increase Versatility by 5.]
			recipe(20034),	-- Crusader [Permanently enchant a melee weapon to often heal for 75 to 124 and increase Strength by 100 for 15 sec. when attacking in melee.]
			recipe(13635),	-- Defense [Permanently enchant a cloak to increase armor by 3.]
			recipe(13915),	-- Demonslaying [Permanently enchant a melee weapon to have a chance of stunning and doing additional damage against demons.]
			recipe(13931),	-- Dodge [Permanently enchant bracers to increase dodge by 5.]
			recipe(25086),	-- Dodge [Permanently enchant a cloak to increase dodge by 8.]
			recipe(13898),	-- Fiery Weapon [Permanently enchant a melee weapon to often strike for 40 additional Fire damage.]
			recipe(25078),	-- Fire Power [Permanently enchant gloves to increase Fire spell power by 9.]
			recipe(13620),	-- Fishing [Permanently enchant gloves to increase Fishing skill by 2.]
			recipe(25074),	-- Frost Power [Permanently enchant gloves to increase Frost spell power by 9.]
			recipe(7857),	-- Health [Permanently enchant chest armor to increase health by 25.]
			recipe(23802),	-- Healing Power [Permanently enchant bracers to increase spell power by 8.]
			recipe(25079),	-- Healing Power [Permanently enchant gloves to increase spell power by 7.]
			recipe(22750),	-- Healing Power [Permanently enchant a melee weapon to increase spell power by 30.]
			recipe(13617),	-- Herbalism [Permanently enchant gloves to increase Herbalism skill by 2.]
			recipe(13822),	-- Intellect [Permanently enchant bracers to increase Intellect by 5.]
			un(5, recipe(20032)),	-- Lifestealing [Permanently enchant a melee weapon to often steal life from the enemy and give it to the wielder.]
			recipe(13607),	-- Mana [Permanently enchant chest armor to increase mana by 20.]
			recipe(13612),	-- Mining [Permanently enchant gloves to increase Mining skill by 2.]
			recipe(13642),	-- Versatility [Permanently enchant bracers to increase Versatility by 5.]
			recipe(20023),	-- Greater Agility [Permanently enchant boots to increase Agility by 7.]
			recipe(20012),	-- Greater Agility [Permanently enchant gloves to increase Agility by 6.]
			recipe(13746),	-- Greater Defense [Permanently enchant a cloak to increase armor by 5.]
			recipe(13640),	-- Greater Health [Permanently enchant chest armor to increase health by 35.]   (No listed locations? - https://www.wowhead.com/spell=13640/greater-health)
			recipe(13937),	-- Greater Impact [Permanently enchant a two-handed melee weapon to do 7 additional points of damage.]
			recipe(20008),	-- Greater Intellect [Permanently enchant bracers to increase Intellect by 7.]
			recipe(13663),	-- Greater Mana [Permanently enchant chest armor to increase mana by 30.]
			recipe(13945),	-- Greater Stamina [Permanently enchant bracers to increase Stamina by 7.]
			recipe(20020),	-- Greater Stamina [Permanently enchant boots to increase Stamina by 7.]
			recipe(20017),	-- Greater Stamina [Permanently enchant a shield to increase Stamina by 7.]
			recipe(20025),	-- Greater Stats [Permanently enchant chest armor to increase all stats by 4.]
			recipe(13939),	-- Greater Strength [Permanently enchant bracers to increase Strength by 7.]
			recipe(20013),	-- Greater Strength [Permanently enchant gloves to increase Strength by 7.]
			recipe(13943),	-- Greater Striking [Permanently enchant a melee weapon to do 4 additional points of damage.]
			recipe(13846),	-- Greater Versatility [Permanently enchant bracers to increase Versatility by 6.]
			recipe(13905),	-- Greater Versatility [Permanently enchant a shield to increase Versatility by 7.]
			recipe(20029),	-- Icy Chill [Permanently enchant a melee weapon to often chill the target, reducing their movement and attack speed.]
			recipe(13695),	-- Impact [Permanently enchant a two-handed melee weapon to do 5 additional points of damage.]
			recipe(20026),	-- Major Health [Permanently enchant chest armor to increase health by 100.]
			recipe(20036),	-- Major Intellect [Permanently enchant a two-handed melee weapon to increase Intellect by 9.]
			recipe(20028),	-- Major Mana [Permanently enchant chest armor to increase mana by 100.]
			recipe(20035),	-- Major Versatility [Permanently enchant a two-handed melee weapon to increase Versatility by 9.]
			recipe(23804),	-- Major Intellect [Permanently enchant a melee weapon to increase Intellect by 22.]
			recipe(23803),	-- Mighty Versatility [Permanently enchant a melee weapon to increase Versatility by 20.]
			recipe(13947),	-- Riding Skill [Permanently enchant gloves to increase mount speed by 2%.]
			recipe(25073),	-- Shadow Power [Permanently enchant gloves to increase shadow spell power by 9.]
			recipe(13698),	-- Skinning [Permanently enchant gloves to increase Skinning skill by 5.]
			recipe(13648),	-- Stamina [Permanently enchant bracers to increase Stamina by 5.]
			recipe(25083),	-- Stealth [Permanently enchant a cloak to increase Agility and dodge by 8.]
			recipe(22749),	-- Spellpower [Permanently enchant a melee weapon to increase spell power by 30.]
			recipe(13836),	-- Stamina [Permanently enchant boots to increase Stamina by 5.]
			recipe(13817),	-- Stamina [Permanently enchant a shield to increase Stamina by 5.]
			recipe(13941),	-- Stats [Permanently enchant chest armor to increase all stats by 3.]
			recipe(13661),	-- Strength [Permanently enchant bracers to increase Strength by 5.]
			recipe(13887),	-- Strength [Permanently enchant gloves to increase Strength by 5.]
			recipe(23799),	-- Strength [Permanently enchant a melee weapon to increase Strength by 15.]
			recipe(13693),	-- Striking [Permanently enchant a melee weapon to do 3 additional points of damage.]
			recipe(25084),	-- Subtlety [Permanently enchant a cloak to decrease threat from all attacks and spells by 2%.]
			recipe(25080),	-- Superior Agility [Permanently enchant gloves to increase Agility by 7.]
			recipe(20015),	-- Superior Defense [Permanently enchant a cloak to increase armor by 7.]
			recipe(13858),	-- Superior Health [Permanently enchant chest armor to increase health by 50.]
			un(5, recipe(20030)),	-- Superior Impact [Permanently enchant a two-handed melee weapon to do 9 additional points of damage.]
			recipe(13917),	-- Superior Mana [Permanently enchant chest armor to increase mana by 40.]
			recipe(20011),	-- Superior Stamina [Permanently enchant bracers to increase Stamina by 9.]
			recipe(20010),	-- Superior Strength [Permanently enchant bracers to increase Strength by 9.]
			recipe(20031),	-- Superior Striking [Permanently enchant a melee weapon to do 5 additional points of damage.]
			recipe(20009),	-- Superior Versatility [Permanently enchant bracers to increase Versatility by 7.]
			recipe(25072),	-- Threat [Permanently enchant gloves to increase threat from all attacks and spells by 2%.]
			recipe(20033),	-- Unholy Weapon [Permanently enchant a melee weapon to often inflict a curse on the target, inflicting Shadow damage and reducing their melee damage.]
			recipe(20024),	-- Versatility [Permanently enchant boots to increase Versatility by 5.]
			recipe(13659),	-- Versatility [Permanently enchant a shield to increase Versatility by 5.]
			recipe(20016),	-- Vitality [Permanently enchant a shield to increase Versatility and Stamina by 10.]
			recipe(21931),	-- Winter's Might [Permanently enchant a melee weapon to increase Frost spell power by 7.]
		}),
		tier(2, {	-- Burning Crusade
			un(1, recipe(28021)),	-- Arcane Dust (Never Implemented)
			recipe(28022),	-- Large Prismatic Shard
			recipe(42615),	-- Small Prismatic Shard
			recipe(28027),	-- Prismatic Sphere
			recipe(28016),	-- Superior Mana Oil
			recipe(28019),	-- Superior Wizard Oil
			recipe(45765),	-- Void Shatter
			recipe(28028),	-- Void Sphere
			recipe(33996),	-- Assault [Permanently enchant gloves to increase attack power by 13.]
			recipe(28004),	-- Battlemaster [Permanently enchant a melee weapon to occasionally heal nearby party members for 76 to 126 when attacking in melee.]
			recipe(33993),	-- Blasting [Permanently enchant gloves to increase critical strike by 10.]
			recipe(34008),	-- Boar's Speed [Permanently enchant boots to increase movement speed by 8% and Stamina by 10.]
			recipe(27899),	-- Brawn [Permanently enchant bracers to increase Strength by 12.]
			recipe(34007),	-- Cat's Swiftness [Permanently enchant boots to increase movement speed by 8% and Agility by 7.]
			recipe(27951),	-- Dexterity [Permanently enchant boots to increase Agility by 8.]
			recipe(46594),	-- Dodge [Permanently enchant chest armor to increase dodge by 8.]
			recipe(42974),	-- Executioner [Permanently enchant a melee weapon to occasionally grant you 60 critical strike.]
			recipe(27957),	-- Exceptional Health [Permanently enchant chest armor to increase health by 120.]
			recipe(27960),	-- Exceptional Stats [Permanently enchant chest armor to increase all stats by 3.]
			recipe(27950),	-- Fortitude [Permanently enchant boots to increase Stamina by 12.]
			recipe(27914),	-- Fortitude [Permanently enchant bracers to increase Stamina by 12.]
			recipe(34004),	-- Greater Agility [Permanently enchant a cloak to increase Agility by 9.]
			recipe(42620),	-- Greater Agility [Permanently enchant a melee weapon to increase Agility by 20.]
			recipe(27906),	-- Greater Dodge [Permanently enchant bracers to increase dodge by 6.]
			recipe(47051),	-- Greater Dodge [Permanently enchant a cloak to increase dodge by 9.]
			recipe(27945),	-- Intellect [Permanently enchant a shield to increase Intellect by 12.]
			recipe(34002),	-- Lesser Assault [Permanently enchant bracers to increase attack power by 8. Cannot be applied to items higher than level 600.]
			recipe(27944),	-- Lesser Dodge [Permanently enchant a shield to increase dodge by 12.]
			recipe(27977),	-- Major Agility [Permanently enchant a two-handed melee weapon to increase Agility by 35.]
			recipe(27961),	-- Major Armor [Permanently enchant a cloak to increase armor by 9.]
			recipe(33999),	-- Major Healing [Permanently enchant gloves to increase spell power by 15.]
			recipe(34010),	-- Major Healing [Permanently enchant a melee weapon to increase spell power by 20.]
			recipe(34001),	-- Major Intellect [Permanently enchant bracers to increase Intellect by 10.]
			recipe(27968),	-- Major Intellect [Permanently enchant a melee weapon to increase Intellect by 30.]
			recipe(33992),	-- Major Resilience [Permanently enchant chest armor to increase PvP Resilience by 8.]
			recipe(33997),	-- Major Spellpower [Permanently enchant gloves to increase spell power by 15]
			recipe(27975),	-- Major Spellpower [Permanently enchant a melee weapon to increase spell power by 40.]
			recipe(34009),	-- Major Stamina [Permanently enchant a shield to increase Stamina by 18.]
			recipe(33995),	-- Major Strength [Permanently enchant gloves to increase Strength by 8.]
			recipe(27967),	-- Major Striking [Permanently enchant a melee weapon to do 7 additional points of damage.]
			recipe(33990),	-- Major Versatility [Permanently enchant chest armor to increase Versatility by 16.]
			recipe(27984),	-- Mongoose [Permanently enchant a melee weapon to occasionally increase Agility by 60 and haste by 15.]
			recipe(27946),	-- Parry [Permanently enchant a shield to increase parry by 7.]
			recipe(27972),	-- Potency [Permanently enchant a melee weapon to increase Strength by 20.]
			recipe(33994),	-- Precise Strikes [Permanently enchant gloves to increase crit by 15.]
			recipe(34003),	-- PvP Power [Permanently enchant a cloak to increase PvP power by 16.]
			recipe(44383),	-- Resilience [Permanently enchant a shield to increase PvP Resilience by 12.]
			recipe(27971),	-- Savagery [Permanently enchant a two-handed melee weapon to increase attack power by 35.]
			recipe(27982),	-- Soulfrost [Permanently enchant a melee weapon to increase Frost and Shadow spell power by 25.]
			recipe(27917),	-- Spellpower [Permanently enchant bracers to increase spell power by 11.]
			recipe(28003),	-- Spellsurge [Permanently enchant a melee weapon to make your spells sometimes restore 100 mana to nearby party members.]
			recipe(27905),	-- Stats [Permanently enchant bracers to increase all stats by 3.]
			recipe(27911),	-- Superior Healing [Permanently enchant bracers to increase spell power by 11.]
			recipe(27981),	-- Sunfire [Permanently enchant a melee weapon to increase Fire and Arcane spell power by 25.]
			recipe(27954),	-- Surefooted [Permanently enchant boots to increase critical strike and haste by 4.]
			recipe(27913),	-- Versatility Prime [Permanently enchant bracers to increase Versatility by 9.]
			recipe(33991),	-- Versatility Prime [Permanently enchant chest armor to increase Versatility by 14.]
			recipe(27948),	-- Vitality [Permanently enchant boots to increase Versatility and Stamina by 4.]
			-- NOTE: STOPPED HERE
			-- https://www.wowhead.com/enchanting#recipes:300+17+10+1
		}),
		tier(3, {	-- Wrath
			recipe(69412),	-- Abyssal Shatter
			recipe(59619),	-- Accuracy [Permanently enchant a melee weapon to increase critical strike by 12.]
			recipe(71692),	-- Angler [Permanently enchant gloves to increase Fishing skill by 5.]
			recipe(44625),	-- Armsman [Permanently enchant gloves to increase threat caused by 2% and increase parry by 5.]
			recipe(60606),	-- Assault [Permanently enchant boots to increase attack power by 8.]
			recipe(60616),	-- Assault [Permanently enchant bracers to increase attack power by 9.]
			recipe(59621),	-- Berserking [Permanently enchant a melee weapon to sometimes increase your attack power by 75, but at the cost of reduced armor.]
			recipe(59625),	-- Black Magic [Permanently enchant a melee weapon to cause your harmful spells to sometimes increase haste by 62.]
			recipe(64441),	-- Blade Ward [Permanently enchant a weapon to sometimes grant Blade Warding when striking an enemy.  Blade Warding increases your parry by 100 and inflicts 286 to 315 damage on your next parry.]
			recipe(64579),	-- Blood Draining [Permanently enchant your weapon to sometimes grant Blood Reserve when striking an enemy or inflicting damage with bleed attacks.  When you fall below 35% health, Blood Reserve restores 180 to 219 health.  Lasts 20 sec and stacks up to 5 times.]
			recipe(60668),	-- Crusher [Permanently enchant gloves to increase attack power by 20.]
			recipe(44489),	-- Dodge [Permanently enchant a shield to increase dodge by 15.]
			recipe(44633),	-- Exceptional Agility [Permanently enchant a melee weapon to increase Agility by 13.]
			recipe(44555),	-- Exceptional Intellect [Permanently enchant bracers to increase Intellect by 8.]
			recipe(27958),	-- Exceptional Mana [Permanently enchant chest armor to increase mana by 120.]
			recipe(44588),	-- Exceptional Resilience [Permanently enchant chest armor to increase PvP Resilience by 10.]
			recipe(44592),	-- Exceptional Spellpower [Permanently enchant gloves to increase spell power by 12.]
			recipe(44629),	-- Exceptional Spellpower [Permanently enchant a melee weapon to increase spell power by 25.]
			recipe(44510),	-- Exceptional Versatility [Permanently enchant a melee weapon to increase Versatility by 23.]
			recipe(44506),	-- Gatherer [Permanently enchant gloves to increase Herbalism, Mining, and Skinning skills by 5.]
			recipe(44621),	-- Giant Slayer [Permanently enchant a melee weapon to have a chance of reducing movement speed and doing additional damage against giants.]
			recipe(44575),	-- Greater Assault [Permanently enchant bracers to increase attack power by 14.]
			recipe(60763),	-- Greater Assault [Permanently enchant boots to increase attack power by 10.]
			recipe(44513),	-- Greater Assault [Permanently enchant gloves to increase attack power by 18.]
			un(1, recipe(44612)),	-- Greater Blasting [Permanently enchant gloves to increase critical strike by 16.]
			recipe(47766),	-- Greater Dodge [Permanently enchant chest armor to increase dodge by 11.]
			recipe(44528),	-- Greater Fortitude [Permanently enchant boots to increase Stamina by 13.]
			recipe(60653),	-- Greater Intellect [Permanently enchant a shield to increase Intellect by 13.]
			recipe(60621),	-- Greater Potency [Permanently enchant a melee weapon to increase attack power by 12.]
			recipe(44630),	-- Greater Savagery [Permanently enchant a two-handed weapon to increase attack power by 42.]
			recipe(47898),	-- Greater Speed [Permanently enchant a cloak to increase haste by 12.]
			recipe(44635),	-- Greater Spellpower [Permanently enchant bracers to increase spell power by 13.]
			recipe(62948),	-- Greater Spellpower [Permanently enchant a staff to increase spell power by 41.]
			recipe(44616),	-- Greater Stats [Permanently enchant bracers to increase all stats by 4.]
			recipe(44508),	-- Greater Versatility [Permanently enchant boots to increase Versatility by 9.]
			recipe(44509),	-- Greater Versatility [Permanently enchant chest armor to increase Versatility by 18.]
			recipe(44584),	-- Greater Vitality [Permanently enchant boots to increase Stamina and Versatility by 5.]
			recipe(44598),	-- Haste [Permanently enchant bracers to increase Haste by 12.]
			recipe(44484),	-- Haste [Permanently enchant gloves to increase haste by 8.]
			recipe(44524),	-- Icebreaker [Permanently enchant a melee weapon to sometimes inflict Fire damage.]
			recipe(60623),	-- Icewalker [Permanently enchant boots to increase critical strike by 9.]
			recipe(44576),	-- Lifeward [Permanently enchant a melee weapon to sometimes heal the wielder when striking in melee.]
			recipe(60663),	-- Major Agility [Permanently enchant a cloak to increase Agility by 11.]
			recipe(44529),	-- Major Agility [Permanently enchant gloves to increase your Agility by 18.]
			recipe(62256),	-- Major Stamina [Permanently enchant bracers to increase Stamina by 20.]
			recipe(44593),	-- Major Versatility [Permanently enchant bracers to increase Versatility by 12.]
			recipe(60691),	-- Massacre [Permanently enchant a two-handed weapon to increase attack power by 55.]
			recipe(44492),	-- Mighty Health [Permanently enchant chest armor to increase health by 130.]
			recipe(60714),	-- Mighty Spellpower [Permanently enchant a melee weapon to increase spell power by 32.]
			recipe(47672),	-- Mighty Stamina [Permanently enchant a cloak to increase Stamina by 13.]
			recipe(44582),	-- Minor Power [Permanently enchant a cloak to increase PvP Power by 20.]
			recipe(60692),	-- Powerful Stats [Permanently enchant chest armor to increase all stats by 7.]
			recipe(44488),	-- Precision [Permanently enchant gloves to increase hit by 18.]
			recipe(44595),	-- Scourgebane [Permanently enchant a two-handed melee weapon to increase attack power against Undead by 35.]
			recipe(44631),	-- Shadow Armor [Permanently enchant a cloak to increase Agility by 6 and armor by 6.]
			recipe(60609),	-- Speed [Permanently enchant a cloak to increase haste by 9.]
			recipe(62959),	-- Spellpower [Permanently enchant a staff to increase spell power by 35.]
			recipe(44589),	-- Superior Agility [Permanently enchant boots to increase Agility by 10.]
			recipe(44500),	-- Superior Agility [Permanently enchant a cloak to increase Agility by 10.]
			recipe(44591),	-- Superior Dodge [Permanently enchant a cloak to increase dodge by 11.]
			recipe(60707),	-- Superior Potency [Permanently enchant a melee weapon to increase attack power by 32.]
			recipe(60767),	-- Superior Spellpower [Permanently enchant bracers to increase spell power by 15.]
			recipe(47900),	-- Super Health [Permanently enchant chest armor to increase health by 140.]
			recipe(44623),	-- Super Stats [Permanently enchant chest armor to increase all stats by 5.]
			un(1, recipe(62257)),	-- Titanguard [Permanently enchant a melee weapon to increase Stamina by 25.]
			recipe(47901),	-- Tuskarr's Vitality [Permanently enchant boots to increase movement speed by 8% and Stamina by 12.]
			recipe(47899),	-- Wisdom [Permanently enchant a cloak to reduce threat slightly and increase Versatility by 5.]
		}),
		tier(4, {	-- Cata
			h(recipe(93841)),	-- Enchanted Lantern
			a(recipe(93843)),	-- Magic Lamp
			recipe(104698),	-- Maelstrom Shatter
			recipe(96264),	-- Agility [Permanently enchant bracers to increase Agility by 14.]
			recipe(74252),	-- Assassin's Step [Permanently enchant boots to increase movement speed by 8% and Agility by 9.]
			recipe(74197),	-- Avalanche [Permanently enchant a weapon to often deal 93 to 107 Nature damage to an enemy damaged by your spells or struck by your melee attacks.]
			recipe(74201),	-- Critical Strike [Permanently enchant bracers to increase critical strike by 14.]
			recipe(74230),	-- Critical Strike [Permanently enchant a cloak to increase critical strike by 15.]
			recipe(74189),	-- Earthen Vitality [Permanently enchant boots to increase movement speed by 8% and Stamina by 11. ]
			recipe(74211),	-- Elemental Slayer [Permanently enchant a melee weapon to sometimes disrupt elementals when struck by your melee attacks, dealing Arcane damage and silencing them for 5 sec.]
			recipe(74212),	-- Exceptional Strength [Permanently enchant gloves to increase Strength by 20.]
			recipe(74237),	-- Exceptional Versatility [Permanently enchant bracers to increase Versatility by 14.]
			recipe(74231),	-- Exceptional Versatility [Permanently enchant a chest to increase Versatility by 20.]
			recipe(74248),	-- Greater Critical Strike [Permanently enchant bracers to increase critical strike by 15.]
			recipe(74247),	-- Greater Critical Strike [Permanently enchant a cloak to increase critical strike by 15.]
			recipe(74239),	-- Greater Haste [Permanently enchant bracers to increase haste by 14.]
			recipe(74220),	-- Greater Haste [Permanently enchant gloves to increase haste by 22.]
			recipe(74240),	-- Greater Intellect [Permanently enchant a cloak to increase Intellect by 11.]
			recipe(74255),	-- Greater Mastery [Permanently enchant gloves to increase mastery by 22.]
			recipe(74256),	-- Greater Speed [Permanently enchant bracers to increase haste by 15.]
			recipe(74251),	-- Greater Stamina [Permanently enchant chest armor to increase Stamina by 16.]
			recipe(74199),	-- Haste [Permanently enchant boots to increase haste by 11.]
			recipe(74198),	-- Haste [Permanently enchant gloves to increase haste by 20.]
			recipe(74225),	-- Heartstring [Permanently enchant a weapon to sometimes increase Versatility by 40 for 15 sec when healing or dealing damage with spells.]
			recipe(74223),	-- Hurricane [Permanently enchant a melee weapon to sometimes increase haste by 90 for 12 sec when healing or dealing spell or melee damage.]
			recipe(74202),	-- Intellect [Permanently enchant a cloak to increase Intellect by 11.]
			recipe(74246),	-- Landslide [Permanently enchant a weapon to sometimes increase attack power by 100 for 12 sec when striking in melee.]
			recipe(74253),	-- Lavawalker [Permanently enchant boots to increase movement speed by 8% and mastery by 9.]
			recipe(74192),	-- Lesser Power [Permanently enchant a cloak to increase PvP Power by 18.]
			recipe(74213),	-- Major Agility [Permanently enchant boots to increase Agility by 11.]
			recipe(96261),	-- Major Strength [Permanently enchant bracers to increase Strength by 15.]
			recipe(74238),	-- Mastery [Permanently enchant boots to increase mastery by 9.]
			recipe(74132),	-- Mastery [Permanently enchant gloves to increase mastery by 18.]
			recipe(74226),	-- Mastery [Permanently enchant a shield to increase mastery by 15.]
			recipe(74195),	-- Mending [Permanently enchant a weapon to sometimes heal you when damaging an enemy with spells and melee attacks.]
			recipe(95471),	-- Mighty Agility [Permanently enchant a two-handed weapon to increase Agility by 60.]
			recipe(96262),	-- Mighty Intellect [Permanently enchant bracers to increase Intellect by 14.]
			recipe(74214),	-- Mighty Resilience [Permanently enchant chest armor to increase PvP Resilience by 12.]
			recipe(74191),	-- Mighty Stats [Permanently enchant chest armor to increase all stats by 6.]
			recipe(74254),	-- Mighty Strength [Permanently enchant gloves to increase Strength by 22.]
			recipe(74242),	-- Power Torrent [Permanently enchant a weapon to sometimes increase Intellect by 100 for 12 sec when dealing damage or healing with spells.]
			recipe(74236),	-- Precision [Permanently enchant boots to increase crit by 11.]
			recipe(74232),	-- Precision [Permanently enchant bracers to increase crit by 14.]
			recipe(74234),	-- Protection [Permanently enchant a cloak to increase Stamina by 15.]
			recipe(74207),	-- Protection [Permanently enchant a shield to increase Stamina by 20.]
			recipe(74193),	-- Speed [Permanently enchant bracers to increase haste by 13.]
			recipe(74200),	-- Stamina [Permanently enchant chest armor to increase Stamina by 14.]
			recipe(74229),	-- Superior Dodge [Permanently enchant bracers to increase dodge by 14.]
			recipe(74235),	-- Superior Intellect [Permanently enchant a shield or held item to increase Intellect by 15.]
			recipe(74244),	-- Windwalk [Permanently enchant a weapon to sometimes increase dodge by 120 and movement speed by 10% for 10 sec when striking in melee, stacking with passive movement speed effects.]
		}),
		tier(5, {	-- Mists
			recipe(116498),	-- Ethereal Shard
			recipe(118238),	-- Ethereal Shatter
			recipe(118237),	-- Mysterious Diffusion
			recipe(116497),	-- Mysterious Essence
			recipe(116499),	-- Sha Crystal
			recipe(118239),	-- Sha Shatter
			recipe(104398),	-- Accuracy [Permanently enchants a cloak to increase critical strike by 20.]
			recipe(104409),	-- Blurred Speed [Permanently enchants a pair of boots to increase movement speed slightly and Agility by 10.]
			recipe(104440),	-- Colossus [Permanently enchants a melee weapon to make your damaging melee strikes sometimes activate a Mogu protection spell, absorbing up to 469 damage.]
			recipe(104434),	-- Dancing Steel [Permanently enchants a melee weapon to sometimes increase your Strength or Agility by 103 when dealing melee damage.]
			recipe(104430),	-- Elemental Force [Permanently enchants a melee weapon to sometimes inflict 174 to 201 additional Elemental damage when dealing damage with spells and melee attacks.]
			recipe(104390),	-- Exceptional Strength [Permanently enchants bracers to increase Strength by 16.]
			recipe(104395),	-- Glorious Stats [Permanently enchants chest armor to increase all stats by 9.]
			recipe(104391),	-- Greater Agility [Permanently enchants bracers to increase Agility by 16.]
			recipe(104407),	-- Greater Haste [Permanently enchants a pair of boots to increase haste by 12.]
			recipe(104416),	-- Greater Haste [Permanently enchants gloves to increase haste by 24.]
			recipe(130758),	-- Greater Parry [Permanently enchant a shield to increase parry by 15.]
			recipe(104408),	-- Greater Precision [Permanently enchants a pair of boots to increase crit by 12.]
			recipe(104401),	-- Greater Protection [Permanently enchants a cloak to increase Stamina by 20.]
			recipe(104427),	-- Jade Spirit [Permanently enchants a melee weapon to sometimes increase your Intellect by 83 when healing or dealing damage with spells.  If less than 25% of your mana remains when the effect is triggered, your Versatility will also increase by 38.]
			recipe(104385),	-- Major Dodge [Permanently enchants bracers to increase dodge by 14.]
			recipe(104445),	-- Major Intellect [Permanently enchants a shield or off-hand item to increase Intellect by 25.]
			recipe(104338),	-- Mastery [Permanently enchants bracers to increase mastery by 14.]
			recipe(104393),	-- Mighty Versatility [Permanently enchants chest armor to increase Versatility by 25.]
			recipe(104414),	-- Pandaren's Step [Permanently enchants a pair of boots to increase movement speed slightly and mastery by 10.]
			recipe(104442),	-- River's Song [Permanently enchants a melee weapon to sometimes increase your dodge by 83 for 7 sec when dealing melee damage.]
			recipe(104404),	-- Superior Critical Strike [Permanently enchants a cloak to increase critical strike by 20.]
			recipe(104417),	-- Superior Haste [Permanently enchants gloves to increase haste by 25.]
			recipe(104403),	-- Superior Intellect [Permanently enchants a cloak to increase Intellect by 15.]
			recipe(104420),	-- Superior Mastery [Permanently enchants gloves to increase mastery by 25.]
			recipe(104397),	-- Superior Stamina [Permanently enchants chest armor to increase Stamina by 18.]
			recipe(104389),	-- Super Intellect [Permanently enchants bracers to increase Intellect by 16.]
			recipe(104392),	-- Super Resilience [Permanently enchants chest armor to increase PvP Resilience by 15.]
			recipe(104419),	-- Super Strength [Permanently enchants gloves to increase Strength by 25.]
			recipe(104425),	-- Windsong [Permanently enchants a melee weapon to sometimes increase your critical strike, haste, or mastery by 75 for 12 sec when dealing damage or healing with spells and melee attacks.]
		}),
	}),
});